# Sponsorship options for Teamleader SDK
# Support the development of this open source project

# GitHub Sponsors - Native GitHub integration
github: [mcore-services-bv]

# Buy Me A Coffee - Quick one-time support
custom: ["https://www.buymeacoffee.com/mcoreservices"]
