<?php

namespace McoreServices\TeamleaderSDK\Tests\Feature;

use InvalidArgumentException;
use McoreServices\TeamleaderSDK\Resources\Deals\Orders;
use McoreServices\TeamleaderSDK\TeamleaderSDK;
use McoreServices\TeamleaderSDK\Tests\TestCase;
use PHPUnit\Framework\Attributes\Group;
use ReflectionClass;

/**
 * Asserts the Orders resource against @teamleader/focus-api-specification.
 *
 * The specification is the contract, not Teamleader's human-readable docs and
 * not the API's runtime behaviour — the API answers 200 to filter keys, sort
 * fields and includes it does not recognise, so a resource can declare
 * capabilities it does not have and never fail a response-based test. Every
 * assertion here compares a declaration in the class against a declaration in
 * the specification.
 *
 * The fixture is a mechanical extract, regenerated by
 * tests/Fixtures/specification/generate-spec-fixtures.mjs. Do not hand-edit it
 * to make a test pass: a fixture that disagrees with the SDK is a finding about
 * the SDK.
 *
 * One deliberate divergence is asserted rather than ignored — see
 * test_pagination_is_undeclared_in_the_specification_but_supported.
 */
#[Group('spec-contract')]
class OrdersSpecContractTest extends TestCase
{
    /**
     * Fields the SDK documents that the specification does not declare.
     *
     * `data` is the list container, which the SDK describes in prose rather
     * than as a field. `status` is observed on live records and absent from the
     * specification — established 2026-08-20 on an order carrying
     * "status": "delivered". Anything else appearing here is either a typo or a
     * field invented from the human-readable documentation.
     */
    private const UNDECLARED_BUT_DOCUMENTED = [
        'list' => ['data', 'data[].status'],
        'info' => ['data.status'],
    ];

    private array $spec;

    private TeamleaderSDK $sdk;

    private Orders $orders;

    protected function setUp(): void
    {
        parent::setUp();

        $path = $this->fixturePath('orders.json');

        $this->assertNotNull(
            $path,
            'Specification fixture orders.json not found in any Fixtures/specification '
            .'directory above '.__DIR__.'. Copy it to tests/Fixtures/specification/, or '
            .'regenerate it with: node tests/Fixtures/specification/generate-spec-fixtures.mjs'
        );

        $this->spec = json_decode(file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);

        // A real SDK with a test token, as in the other resource tests. No
        // request is ever sent: the two tests that call list() assert on the
        // exception it raises before building one.
        $this->sdk = new TeamleaderSDK;
        $this->sdk->setAccessToken('test_token');
        $this->orders = $this->sdk->orders();
    }

    /**
     * Locate a fixture by walking up from this file.
     *
     * Done by search rather than by a relative path so the test can sit in
     * tests/Feature, tests/Unit/Resources/Deals or anywhere else without the
     * path needing to be kept in step with it.
     */
    private function fixturePath(string $name): ?string
    {
        $directory = __DIR__;

        while ($directory !== dirname($directory)) {
            $candidate = $directory.'/Fixtures/specification/'.$name;

            if (is_file($candidate)) {
                return $candidate;
            }

            $directory = dirname($directory);
        }

        return null;
    }

    // -- request contract ----------------------------------------------------

    public function test_declared_filters_match_the_specification(): void
    {
        $declared = $this->spec['endpoints']['orders.list']['request']['filters'];
        $supported = array_keys($this->property('commonFilters'));

        sort($supported);

        $this->assertSame(
            $declared,
            $supported,
            'orders.list accepts exactly these filter keys. The API ignores any '
            .'other key and returns the full unfiltered set, so a filter listed '
            .'here that the specification does not declare is a filter that '
            .'silently does nothing.'
        );
    }

    public function test_unsupported_filter_keys_are_rejected_before_the_request(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessageMatches('/orders\.list: updated_since/');

        // Plausible, documented on other resources, and silently ignored here.
        $this->orders->list(['updated_since' => '2026-01-01T00:00:00+00:00']);
    }

    public function test_sorting_is_not_declared_and_not_advertised(): void
    {
        $request = $this->spec['endpoints']['orders.list']['request'];

        $this->assertFalse(
            $request['declares_sort'],
            'The specification has gained a sort parameter for orders.list. '
            .'Set $supportsSorting = true, populate $availableSortFields from '
            .'the declared enum, and build the sort block in list().'
        );

        $this->assertFalse(
            $this->property('supportsSorting'),
            '$supportsSorting must stay false while the endpoint declares no sort.'
        );
    }

    public function test_a_sort_option_is_rejected_rather_than_discarded(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessageMatches('/does not support sorting/');

        // The API accepts this and ignores it — sorting by order_date returns
        // the same first record as no sort at all.
        $this->orders->list([], ['sort' => 'order_date']);
    }

    public function test_sideloading_matches_the_specification(): void
    {
        $request = $this->spec['endpoints']['orders.list']['request'];

        $this->assertSame(
            $request['declares_includes'],
            $this->property('supportsSideloading'),
            '$supportsSideloading must track whether the endpoint declares an '
            .'includes parameter.'
        );

        $available = $this->property('availableIncludes');

        $this->assertTrue(
            array_is_list($available),
            '$availableIncludes must be a flat list, as on every other resource. '
            .'A keyed map changes the shape of getCapabilities() output.'
        );

        // The specification types `includes` as a free-form string and does not
        // enumerate the accepted values, so this is the strongest assertion
        // available: whatever it offers as an example must be one we advertise.
        $this->assertContains(
            $request['includes_example'],
            $available,
            'The include the specification gives as an example is not advertised '
            .'by the resource.'
        );
    }

    public function test_info_requires_an_id_and_accepts_includes(): void
    {
        $request = $this->spec['endpoints']['orders.info']['request'];

        $this->assertSame(['id'], $request['required']);
        $this->assertSame(['id', 'includes'], $request['properties']);
    }

    // -- the one divergence --------------------------------------------------

    /**
     * orders.list is not declared as paginated, but paginates.
     *
     * Verified live on 2026-08-20 against an account holding 30 orders: no page
     * parameter returned 20, size 100 returned all 30, size 100 number 2
     * returned 0, and size 5 returned five records on page 1 and five different
     * records on page 2. An ignored parameter cannot produce that.
     *
     * This test exists so the divergence stays deliberate. If Teamleader
     * documents the parameter, this fails and the explanatory comments on
     * $supportsPagination and list() can be shortened to a normal declaration.
     */
    public function test_pagination_is_undeclared_in_the_specification_but_supported(): void
    {
        $this->assertFalse(
            $this->spec['endpoints']['orders.list']['request']['declares_pagination'],
            'orders.list now declares `page` in specification '
            .$this->spec['specification_version'].'. The divergence documented on '
            .'Orders::$supportsPagination is resolved — trim the comment to a '
            .'plain reference to the specification.'
        );

        $this->assertTrue(
            $this->property('supportsPagination'),
            'Pagination is undeclared but functional. Turning this off returns '
            .'the resource to silently capping every caller at 20 records.'
        );
    }

    public function test_no_pagination_metadata_is_claimed(): void
    {
        $response = $this->spec['endpoints']['orders.list']['response'];

        $this->assertFalse(
            $response['declares_meta'],
            'orders.list now declares a meta block. Check whether it accepts '
            .'includes=pagination, and if so set $requestsPaginationMeta = true '
            .'so all() can use a real total instead of inferring the end of the '
            .'list from a short page.'
        );

        $this->assertFalse(
            $this->property('requestsPaginationMeta'),
            'The endpoint returns no meta block, so the resource must not claim '
            .'one in its generated documentation.'
        );
    }

    // -- response contract ---------------------------------------------------

    public function test_response_structure_documents_every_declared_field(): void
    {
        foreach (['list' => 'orders.list', 'info' => 'orders.info'] as $operation => $endpoint) {
            $declared = array_keys($this->spec['endpoints'][$endpoint]['response']['fields']);
            $documented = array_keys($this->orders->getResponseStructure()[$operation]['fields']);

            $this->assertSame(
                [],
                array_values(array_diff($declared, $documented)),
                "getResponseStructure()['{$operation}'] omits fields the "
                ."specification declares on {$endpoint}."
            );
        }
    }

    public function test_response_structure_documents_nothing_undeclared(): void
    {
        foreach (['list' => 'orders.list', 'info' => 'orders.info'] as $operation => $endpoint) {
            $declared = array_keys($this->spec['endpoints'][$endpoint]['response']['fields']);
            $documented = array_keys($this->orders->getResponseStructure()[$operation]['fields']);

            $extra = array_values(array_diff($documented, $declared, self::UNDECLARED_BUT_DOCUMENTED[$operation]));

            $this->assertSame(
                [],
                $extra,
                "getResponseStructure()['{$operation}'] documents fields the "
                ."specification does not declare on {$endpoint}. Either they were "
                .'taken from the human-readable documentation, or they are real '
                .'and undeclared — in which case verify against a live record and '
                .'add them to UNDECLARED_BUT_DOCUMENTED with a note.'
            );
        }
    }

    public function test_undeclared_fields_are_flagged_as_undeclared(): void
    {
        $structure = $this->orders->getResponseStructure();

        foreach (self::UNDECLARED_BUT_DOCUMENTED as $operation => $fields) {
            foreach ($fields as $field) {
                if ($field === 'data') {
                    continue; // The list container, not a record field.
                }

                $this->assertStringContainsString(
                    'not declared in the API specification',
                    $structure[$operation]['fields'][$field],
                    "{$field} is not in the specification, so its description "
                    .'must say so rather than presenting it as documented.'
                );
            }
        }
    }

    public function test_order_number_is_documented_as_a_number(): void
    {
        $spec = $this->spec['endpoints']['orders.list']['response']['fields']['data[].order_number'];
        $documented = $this->orders->getResponseStructure()['list']['fields']['data[].order_number'];

        $this->assertStringContainsString('number', $spec);
        $this->assertStringContainsString(
            'integer',
            $documented,
            'order_number is a number in the specification and an integer on live '
            .'records. The description must not leave the type to the reader.'
        );
    }

    public function test_payment_term_types_match_the_declared_enum(): void
    {
        $declared = $this->declaredEnum('orders.list', 'data[].payment_term.type');
        $offered = $this->orders->getPaymentTermTypes();
        sort($offered);

        $this->assertSame(
            $declared,
            $offered,
            'getPaymentTermTypes() must match the enum the specification declares.'
        );
    }

    public function test_supplier_types_match_the_declared_enum(): void
    {
        $declared = $this->declaredEnum('orders.list', 'data[].supplier.type');
        $offered = $this->orders->getSupplierTypes();
        sort($offered);

        $this->assertSame(
            $declared,
            $offered,
            'getSupplierTypes() must match the enum the specification declares.'
        );
    }

    /**
     * Where the specification enumerates a value set, the field description
     * must list the whole set.
     *
     * Currency is excluded: 23 codes in a field description is noise, and the
     * Currencies resource covers them.
     */
    public function test_documented_descriptions_list_every_declared_enum_value(): void
    {
        $incomplete = [];

        foreach (['list' => 'orders.list', 'info' => 'orders.info'] as $operation => $endpoint) {
            $documented = $this->orders->getResponseStructure()[$operation]['fields'];

            foreach ($this->spec['endpoints'][$endpoint]['response']['fields'] as $field => $type) {
                if (! str_contains($type, 'enum: ') || str_ends_with($field, '.currency')) {
                    continue;
                }

                foreach (explode('|', substr($type, strpos($type, 'enum: ') + 6)) as $value) {
                    if (! str_contains($documented[$field] ?? '', $value)) {
                        $incomplete[] = "{$field} omits '{$value}'";
                    }
                }
            }
        }

        $this->assertSame(
            [],
            $incomplete,
            'A field description that lists some accepted values but not all is '
            .'worse than one that lists none — it reads as complete.'
        );
    }

    // -- capability flags ----------------------------------------------------

    public function test_write_operations_are_not_advertised(): void
    {
        foreach (['orders.create', 'orders.update', 'orders.delete'] as $endpoint) {
            $this->assertArrayNotHasKey(
                $endpoint,
                $this->spec['endpoints'],
                "The fixture now covers {$endpoint} — review the read-only flags."
            );
        }

        foreach (['supportsCreation', 'supportsUpdate', 'supportsDeletion', 'supportsBatch'] as $flag) {
            $this->assertFalse(
                $this->property($flag),
                "Orders is read-only: \${$flag} must be false."
            );
        }
    }

    public function test_capabilities_report_matches_the_declared_flags(): void
    {
        $capabilities = $this->orders->getCapabilities();

        $this->assertTrue($capabilities['supports_pagination']);
        $this->assertTrue($capabilities['supports_filtering']);
        $this->assertFalse($capabilities['supports_sorting']);
        $this->assertTrue($capabilities['supports_sideloading']);
        $this->assertSame('orders', $capabilities['endpoint']);
    }

    public function test_every_usage_example_calls_a_method_that_exists(): void
    {
        $missing = [];

        foreach ($this->property('usageExamples') as $key => $example) {
            preg_match_all('/->([a-zA-Z_][a-zA-Z0-9_]*)\(/', $example['code'], $matches);

            foreach ($matches[1] as $method) {
                if ($method === 'orders') {
                    continue; // The facade accessor, not a method on this class.
                }

                if (! method_exists($this->orders, $method)) {
                    $missing[] = "{$key}: {$method}()";
                }
            }
        }

        $this->assertSame(
            [],
            $missing,
            'Usage examples published by the SDK must run. Three have been found '
            .'unrunnable so far — Deals::withCustomer(), and ->include() on both '
            .'Orders and Quotations.'
        );
    }

    /**
     * Read a declared enum out of the fixture, sorted.
     *
     * Derived rather than written out, so a value Teamleader adds or removes
     * surfaces as a failure instead of sitting in a stale literal.
     */
    private function declaredEnum(string $endpoint, string $field): array
    {
        $type = $this->spec['endpoints'][$endpoint]['response']['fields'][$field] ?? '';

        $this->assertStringContainsString(
            'enum: ',
            $type,
            "The specification no longer declares an enum for {$field}."
        );

        $values = explode('|', substr($type, strpos($type, 'enum: ') + 6));
        sort($values);

        return $values;
    }

    /**
     * Read a protected declaration off the resource.
     */
    private function property(string $name): mixed
    {
        return (new ReflectionClass(Orders::class))
            ->getProperty($name)
            ->getValue($this->orders);
    }
}
