<?php

declare(strict_types=1);

namespace McoreServices\TeamleaderSDK\Tests\Support\Docs;

use McoreServices\TeamleaderSDK\Resources\Resource;
use McoreServices\TeamleaderSDK\Tests\Support\Spec\SdkInventory;
use McoreServices\TeamleaderSDK\Tests\Support\Spec\SpecContract;
use ReflectionClass;
use ReflectionClassConstant;
use ReflectionMethod;
use ReflectionNamedType;
use ReflectionParameter;
use RuntimeException;

/**
 * Builds the API reference in docs/reference from the resource classes.
 *
 * Everything on a reference page is read from code — the registry on
 * TeamleaderSDK, the resource's declared filters, sort fields and includes,
 * its public constants, its public methods and their docblocks — so the
 * reference cannot describe behaviour the SDK does not have. Nothing is
 * constructed and no Laravel app is booted.
 *
 * The output is deterministic: the same code produces the same bytes, which is
 * what lets `bin/docs --check` fail CI when a resource changes without its
 * page being regenerated.
 *
 * Development tooling only — excluded from the Composer dist archive.
 */
final class ReferenceGenerator
{
    public const SUMMARY_START = '<!-- reference:start -->';

    public const SUMMARY_END = '<!-- reference:end -->';

    /** Namespace segment => display name, in the order the reference lists them */
    private const CATEGORIES = [
        'CRM' => 'CRM',
        'Deals' => 'Deals',
        'Invoicing' => 'Invoicing',
        'Expenses' => 'Expenses',
        'Products' => 'Products',
        'Projects' => 'Projects',
        'Tasks' => 'Tasks',
        'TimeTracking' => 'Time Tracking',
        'Planning' => 'Planning',
        'Calendar' => 'Calendar',
        'Tickets' => 'Tickets',
        'General' => 'General',
        'Files' => 'Files',
        'Templates' => 'Templates',
        'Other' => 'Other',
    ];

    /**
     * Public methods every resource inherits or that only describe the
     * resource. They are covered once in the guides, not on every page.
     */
    private const INTROSPECTION_METHODS = [
        '__construct', 'with', 'getcapabilities', 'getdocumentation', 'generatemarkdowndocs',
        'getavailablesortfields', 'getavailableincludes', 'getcommonfilters', 'getusageexamples',
        'getresponseformat', 'getsuggestedincludes', 'getratelimitcost', 'getpaginationbehaviour',
    ];

    private const SMALL_WORDS = ['of', 'and', 'or', 'the', 'to', 'in', 'on'];

    private const GENERATED_NOTICE = '<!-- Generated by bin/docs from the resource classes. Do not edit: run `composer docs:build`. -->';

    public function __construct(
        private readonly SdkInventory $inventory,
        private readonly SpecContract $spec,
    ) {}

    public static function defaultDocsPath(): string
    {
        return dirname(__DIR__, 3).'/docs';
    }

    /**
     * Every generated reference file, relative to docs/, => its content.
     *
     * @return array<string, string>
     */
    public function pages(): array
    {
        $pages = [];

        foreach ($this->grouped() as $resources) {
            foreach ($resources as $resource) {
                $pages[$this->pagePath($resource)] = $this->resourcePage($resource);
            }
        }

        $pages['reference/README.md'] = $this->indexPage();
        ksort($pages);

        return $pages;
    }

    /**
     * The reference part of SUMMARY.md, between the two markers.
     */
    public function summarySection(): string
    {
        $lines = [self::SUMMARY_START, '', '## API Reference', '', '* [All resources](reference/README.md)'];

        foreach ($this->grouped() as $category => $resources) {
            $lines[] = '* '.self::CATEGORIES[$category];

            foreach ($resources as $resource) {
                $lines[] = '  * ['.$this->title($resource).']('.$this->pagePath($resource).')';
            }
        }

        $lines[] = '';
        $lines[] = self::SUMMARY_END;

        return implode("\n", $lines);
    }

    /**
     * SUMMARY.md with its reference section replaced.
     *
     * @throws RuntimeException When the markers are missing
     */
    public function summary(string $current): string
    {
        $start = strpos($current, self::SUMMARY_START);
        $end = strpos($current, self::SUMMARY_END);

        if ($start === false || $end === false || $end < $start) {
            throw new RuntimeException('docs/SUMMARY.md needs the '.self::SUMMARY_START.' and '.self::SUMMARY_END.' markers.');
        }

        return substr($current, 0, $start).$this->summarySection().substr($current, $end + strlen(self::SUMMARY_END));
    }

    /**
     * Write every page and the SUMMARY section. Pages for resources that no
     * longer exist are removed.
     *
     * @return list<string> Paths written or removed, relative to docs/
     */
    public function write(string $docsPath): array
    {
        $changed = [];

        foreach ($this->diff($docsPath) as $path => $state) {
            $absolute = $docsPath.'/'.$path;

            if ($state === 'stale') {
                unlink($absolute);
            } else {
                if (! is_dir(dirname($absolute))) {
                    mkdir(dirname($absolute), 0755, true);
                }

                file_put_contents($absolute, $this->expected($docsPath)[$path]);
            }

            $changed[] = $path;
        }

        return $changed;
    }

    /**
     * What differs between the committed docs and what the code produces.
     *
     * @return array<string, 'missing'|'outdated'|'stale'> Relative path => state
     */
    public function diff(string $docsPath): array
    {
        $expected = $this->expected($docsPath);
        $diff = [];

        foreach ($expected as $path => $content) {
            $absolute = $docsPath.'/'.$path;

            if (! is_file($absolute)) {
                $diff[$path] = 'missing';
            } elseif (file_get_contents($absolute) !== $content) {
                $diff[$path] = 'outdated';
            }
        }

        foreach ($this->committedReferencePages($docsPath) as $path) {
            if (! isset($expected[$path])) {
                $diff[$path] = 'stale';
            }
        }

        ksort($diff);

        return $diff;
    }

    /**
     * @return array<string, string>
     */
    private function expected(string $docsPath): array
    {
        $summaryPath = $docsPath.'/SUMMARY.md';

        if (! is_file($summaryPath)) {
            throw new RuntimeException('docs/SUMMARY.md not found.');
        }

        return [...$this->pages(), 'SUMMARY.md' => $this->summary((string) file_get_contents($summaryPath))];
    }

    /**
     * @return list<string>
     */
    private function committedReferencePages(string $docsPath): array
    {
        $root = $docsPath.'/reference';

        if (! is_dir($root)) {
            return [];
        }

        $paths = [];
        $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($root, \FilesystemIterator::SKIP_DOTS));

        foreach ($iterator as $file) {
            if ($file->isFile() && $file->getExtension() === 'md') {
                $paths[] = 'reference/'.str_replace('\\', '/', substr($file->getPathname(), strlen($root) + 1));
            }
        }

        sort($paths);

        return $paths;
    }

    /**
     * Resources grouped by category, categories and resources in reference order.
     *
     * @return array<string, list<array<string, mixed>>>
     */
    private function grouped(): array
    {
        $grouped = array_fill_keys(array_keys(self::CATEGORIES), []);

        foreach ($this->inventory->resources() as $resource) {
            if (! isset(self::CATEGORIES[$resource['category']])) {
                throw new RuntimeException("Category {$resource['category']} has no display name in ReferenceGenerator::CATEGORIES.");
            }

            $grouped[$resource['category']][] = $resource;
        }

        foreach ($grouped as &$resources) {
            usort($resources, fn ($a, $b) => strcmp($this->title($a), $this->title($b)));
        }

        return array_filter($grouped);
    }

    private function pagePath(array $resource): string
    {
        return 'reference/'.$this->slug(self::CATEGORIES[$resource['category']]).'/'.$this->slug($this->title($resource)).'.md';
    }

    /**
     * `unitsOfMeasure` → `Units of Measure`
     */
    private function title(array $resource): string
    {
        $words = preg_split('/(?<=[a-z])(?=[A-Z])/', $resource['key']) ?: [$resource['key']];

        $words = array_map(
            fn (string $word, int $i) => $i > 0 && in_array(strtolower($word), self::SMALL_WORDS, true) ? strtolower($word) : ucfirst($word),
            $words,
            array_keys($words)
        );

        return implode(' ', $words);
    }

    private function slug(string $title): string
    {
        return trim((string) preg_replace('/[^a-z0-9]+/', '-', strtolower($title)), '-');
    }

    // ── Index ────────────────────────────────────────────────────────────

    private function indexPage(): string
    {
        $out = [
            self::GENERATED_NOTICE,
            '',
            '# API Reference',
            '',
            'One page per resource, generated from the SDK source. Each page lists the facade',
            'method, the API endpoints the resource calls, the filters, sort fields and',
            'includes it accepts, the constants that hold its accepted values, and every',
            'public method.',
            '',
            'Filters, sort fields, includes and body fields are checked against',
            '`@teamleader/focus-api-specification` **'.$this->spec->version().'** — see',
            '[Specification parity](../project/specification-parity.md). Anything not listed',
            'on a page throws an `InvalidArgumentException` before a request is sent.',
            '',
        ];

        foreach ($this->grouped() as $category => $resources) {
            $out[] = '## '.self::CATEGORIES[$category];
            $out[] = '';
            $out[] = '| Resource | Facade | Create | Update | Delete | Filter | Sort | Includes |';
            $out[] = '|---|---|:-:|:-:|:-:|:-:|:-:|:-:|';

            foreach ($resources as $resource) {
                $link = substr($this->pagePath($resource), strlen('reference/'));
                $supports = $resource['supports'];

                $out[] = sprintf(
                    '| [%s](%s) | `%s()` | %s | %s | %s | %s | %s | %s |',
                    $this->title($resource),
                    $link,
                    $resource['key'],
                    $this->tick($supports['creation']),
                    $this->tick($supports['update']),
                    $this->tick($supports['deletion']),
                    $this->tick($resource['filters'] !== []),
                    $this->tick($resource['sort_fields'] !== []),
                    $this->tick($this->includeNames($resource['includes']) !== [] || ($resource['info_includes'] ?? []) !== []),
                );
            }

            $out[] = '';
        }

        $out = [...$out, ...$this->includesTable()];

        $aliases = $this->inventory->deprecatedAliases();

        if ($aliases !== []) {
            $out[] = '## Deprecated resource keys';
            $out[] = '';
            $out[] = 'These keys still resolve, with an `E_USER_DEPRECATED` notice, and are removed in v3.0.';
            $out[] = '';
            $out[] = '| Deprecated | Use |';
            $out[] = '|---|---|';

            ksort($aliases);

            foreach ($aliases as $old => $new) {
                $out[] = "| `{$old}()` | `{$new}()` |";
            }

            $out[] = '';
        }

        return implode("\n", $out);
    }

    /**
     * @return list<string>
     */
    private function includesTable(): array
    {
        $rows = [];

        foreach ($this->grouped() as $resources) {
            foreach ($resources as $resource) {
                $list = $this->includeNames($resource['includes']);
                $info = $resource['info_includes'] ?? $list;

                if ($list === [] && $info === []) {
                    continue;
                }

                $rows[] = sprintf(
                    '| [%s](%s) | %s | %s |',
                    $this->title($resource),
                    substr($this->pagePath($resource), strlen('reference/')),
                    $this->codeList($list),
                    $this->codeList($info),
                );
            }
        }

        return [
            '## Includes',
            '',
            'Every resource that accepts sideloaded includes. No other resource takes any; see',
            '[Sideloading](../guides/sideloading.md).',
            '',
            '| Resource | `list()` | `info()` |',
            '|---|---|---|',
            ...$rows,
            '',
        ];
    }

    // ── Resource page ────────────────────────────────────────────────────

    private function resourcePage(array $resource): string
    {
        $reflection = new ReflectionClass($resource['class']);
        $defaults = $reflection->getDefaultProperties();
        $supports = $resource['supports'];

        $out = [
            self::GENERATED_NOTICE,
            '',
            '# '.$this->title($resource),
            '',
        ];

        if (($defaults['description'] ?? '') !== '') {
            $out[] = rtrim($defaults['description'], '.').'.';
            $out[] = '';
        }

        $classDoc = $this->docblock((string) $reflection->getDocComment());

        if ($classDoc['description'] !== '') {
            $out[] = $classDoc['description'];
            $out[] = '';
        }

        $aliases = [...$resource['aliases'], ...array_keys(array_filter(
            $this->inventory->deprecatedAliases(),
            fn (string $canonical) => $canonical === $resource['key']
        ))];
        sort($aliases);

        $out[] = '```php';
        $out[] = "Teamleader::{$resource['key']}()";
        $out[] = '```';
        $out[] = '';
        $out[] = '| | |';
        $out[] = '|---|---|';
        $out[] = '| Class | `'.$resource['class'].'` |';

        if ($aliases !== []) {
            $out[] = '| Also available as | '.implode(', ', array_map(fn ($a) => "`{$a}()`", $aliases)).' |';
        }

        $out[] = '| Create / update / delete | '.$this->tick($supports['creation']).' / '.$this->tick($supports['update']).' / '.$this->tick($supports['deletion']).' |';
        $out[] = '| Pagination | '.$this->paginationLabel($supports).' |';
        $out[] = '';

        $out = [...$out, ...$this->endpointsSection($resource)];
        $out = [...$out, ...$this->filtersSection($resource, $defaults)];
        $out = [...$out, ...$this->sortSection($resource, $defaults)];
        $out = [...$out, ...$this->includesSection($resource, $defaults)];
        $out = [...$out, ...$this->constantsSection($reflection)];
        $out = [...$out, ...$this->methodsSection($reflection)];
        $out = [...$out, ...$this->examplesSection($defaults['usageExamples'] ?? [])];

        return implode("\n", $out);
    }

    private function paginationLabel(array $supports): string
    {
        if (! $supports['pagination']) {
            return 'No';
        }

        return $supports['pagination_meta']
            ? '`page_size` / `page_number`; the response includes `meta` with totals'
            : '`page_size` / `page_number`; no totals — a short page is the last one';
    }

    /**
     * @return list<string>
     */
    private function endpointsSection(array $resource): array
    {
        $endpoints = $resource['endpoints'];
        sort($endpoints);

        if ($endpoints === []) {
            return [];
        }

        $out = ['## Endpoints', ''];

        foreach ($endpoints as $endpoint) {
            $note = $this->spec->has($endpoint) && $this->spec->isDeprecated($endpoint) ? ' — deprecated by Teamleader' : '';
            $out[] = "- `{$endpoint}`{$note}";
        }

        $out[] = '';

        return $out;
    }

    /**
     * @return list<string>
     */
    private function filtersSection(array $resource, array $defaults): array
    {
        if ($resource['filters'] === []) {
            return ['## Filters', '', '`list()` takes no filters.', ''];
        }

        return [
            '## Filters',
            '',
            'Passed as the first argument to `list()`. Any other key throws.',
            '',
            ...$this->nameTable($defaults['commonFilters'] ?? [], 'Filter'),
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function sortSection(array $resource, array $defaults): array
    {
        if ($resource['sort_fields'] === []) {
            return [];
        }

        return [
            '## Sorting',
            '',
            'Pass `sort` (and optionally `sort_order`) in the options. Any other field throws.',
            '',
            ...$this->nameTable($defaults['availableSortFields'] ?? [], 'Field'),
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function includesSection(array $resource, array $defaults): array
    {
        $list = $this->includeNames($resource['includes']);
        $info = $resource['info_includes'];

        if ($list === [] && ($info ?? []) === []) {
            return [];
        }

        $out = ['## Includes', ''];

        if ($info === null) {
            $out[] = '`list()` and `info()` accept the same includes:';
            $out[] = '';
            $out = [...$out, ...$this->nameTable($defaults['availableIncludes'] ?? [], 'Include')];
        } else {
            $out[] = '| Endpoint | Includes |';
            $out[] = '|---|---|';
            $out[] = '| `list()` | '.($list === [] ? 'none' : $this->codeList($list)).' |';
            $out[] = '| `info()` | '.($info === [] ? 'none' : $this->codeList($info)).' |';
        }

        $out[] = '';

        return $out;
    }

    /**
     * Public constants declared on the resource or a shared base class below
     * Resource: field lists and the values an enum accepts.
     *
     * @return list<string>
     */
    private function constantsSection(ReflectionClass $reflection): array
    {
        $rows = [];

        foreach ($reflection->getReflectionConstants(ReflectionClassConstant::IS_PUBLIC) as $constant) {
            if ($constant->getDeclaringClass()->getName() === Resource::class) {
                continue;
            }

            $value = $constant->getValue();

            if (! is_array($value) || $value === [] || ! array_is_list($value)) {
                continue;
            }

            $rows[$constant->getName()] = '| `'.$constant->getName().'` | '.$this->codeList(array_map('strval', $value)).' |';
        }

        if ($rows === []) {
            return [];
        }

        ksort($rows);

        return [
            '## Accepted values',
            '',
            'Public constants on the class. Body fields and enum values outside these lists',
            'throw before the request is sent.',
            '',
            '| Constant | Values |',
            '|---|---|',
            ...array_values($rows),
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function methodsSection(ReflectionClass $reflection): array
    {
        $methods = [];

        foreach ($reflection->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
            if ($method->isStatic()
                || $method->getDeclaringClass()->getName() === Resource::class
                || in_array(strtolower($method->getName()), self::INTROSPECTION_METHODS, true)) {
                continue;
            }

            $methods[$method->getName()] = $method;
        }

        if ($methods === []) {
            return [];
        }

        $out = ['## Methods', ''];

        foreach ($methods as $method) {
            $doc = $this->docblock((string) $method->getDocComment());

            $out[] = '### `'.$method->getName().'()`';
            $out[] = '';

            if ($doc['deprecated'] !== null) {
                $out[] = '> **Deprecated**'.($doc['deprecated'] !== '' ? ' '.$doc['deprecated'] : '');
                $out[] = '';
            }

            $out[] = '```php';
            $out[] = $this->signature($method);
            $out[] = '```';
            $out[] = '';

            if ($doc['description'] !== '') {
                $out[] = $doc['description'];
                $out[] = '';
            }

            $params = array_filter($doc['params']);

            if ($params !== []) {
                foreach ($params as $name => $text) {
                    $out[] = "- `\${$name}` — {$text}";
                }

                $out[] = '';
            }

            if ($doc['throws'] !== []) {
                foreach ($doc['throws'] as $throws) {
                    $out[] = '**Throws** '.$throws;
                    $out[] = '';
                }
            }
        }

        return $out;
    }

    /**
     * @return list<string>
     */
    private function examplesSection(array $examples): array
    {
        $examples = array_filter($examples, fn ($example) => is_array($example) && isset($example['code']));

        if ($examples === []) {
            return [];
        }

        $out = ['## Examples', ''];

        foreach ($examples as $example) {
            if (($example['description'] ?? '') !== '') {
                $out[] = rtrim($example['description'], '.:').':';
                $out[] = '';
            }

            $out[] = '```php';
            $out[] = $this->resolveExample((string) $example['code']);
            $out[] = '```';
            $out[] = '';
        }

        return $out;
    }

    /**
     * Usage examples are written against `$teamleader`; the docs use the facade.
     */
    private function resolveExample(string $code): string
    {
        return str_replace('$teamleader->', 'Teamleader::', rtrim($code));
    }

    // ── Formatting helpers ───────────────────────────────────────────────

    /**
     * A name list, or a name => description map, as a Markdown table.
     *
     * @return list<string>
     */
    private function nameTable(array $declared, string $heading): array
    {
        if (array_is_list($declared)) {
            $names = array_map('strval', $declared);
            sort($names);

            return [$this->codeList($names)];
        }

        ksort($declared);
        $rows = ["| {$heading} | Description |", '|---|---|'];

        foreach ($declared as $name => $description) {
            $text = is_array($description) ? implode(', ', array_map('strval', $description)) : (string) $description;
            $rows[] = '| `'.$name.'` | '.str_replace(['<', '>'], ['&lt;', '&gt;'], $this->cell($text)).' |';
        }

        return $rows;
    }

    /**
     * @return list<string>
     */
    private function includeNames(array $includes): array
    {
        $names = array_is_list($includes) ? $includes : array_keys($includes);
        $names = array_map('strval', $names);
        sort($names);

        return $names;
    }

    private function codeList(array $values): string
    {
        return $values === [] ? '—' : implode(', ', array_map(fn ($v) => '`'.$v.'`', $values));
    }

    private function tick(bool $value): string
    {
        return $value ? '✓' : '—';
    }

    private function cell(string $text): string
    {
        return str_replace(['|', "\n"], ['\|', ' '], trim($text));
    }

    /**
     * `{@see LegacyProjects}` → `` `LegacyProjects` ``
     */
    private function inlineTags(string $text): string
    {
        return (string) preg_replace_callback(
            '/\{@(?:see|link)\s+([^}\s]+)[^}]*\}/',
            fn (array $match) => '`'.ltrim($this->shortConstant($match[1]), '\\').'`',
            $text
        );
    }

    private function signature(ReflectionMethod $method): string
    {
        $params = array_map(fn (ReflectionParameter $p) => $this->parameter($p), $method->getParameters());
        $return = $method->hasReturnType() ? ': '.$this->type($method->getReturnType(), $method->getDeclaringClass()) : '';

        return $method->getName().'('.implode(', ', $params).')'.$return;
    }

    private function parameter(ReflectionParameter $parameter): string
    {
        $out = $parameter->hasType() ? $this->type($parameter->getType(), $parameter->getDeclaringClass()).' ' : '';
        $out .= ($parameter->isVariadic() ? '...' : '').'$'.$parameter->getName();

        if ($parameter->isDefaultValueAvailable()) {
            $out .= ' = '.($parameter->isDefaultValueConstant()
                ? $this->shortConstant((string) $parameter->getDefaultValueConstantName())
                : $this->literal($parameter->getDefaultValue()));
        }

        return $out;
    }

    /**
     * A type as it would be written in the declaring class.
     *
     * `self`, `static` and `parent` are normalised explicitly. PHP 8.5
     * reports a `self` type through reflection differently from 8.2 – 8.4,
     * which made the generated pages differ per PHP version and failed
     * `docs:check` on 8.5 only. The declaring class's own name is rendered as
     * `self` for the same reason, so every supported version produces the
     * same bytes.
     */
    private function type(?\ReflectionType $type, ?ReflectionClass $context = null): string
    {
        if ($type instanceof ReflectionNamedType) {
            $raw = ltrim($type->getName(), '\\');
            $lower = strtolower($raw);

            $name = match (true) {
                in_array($lower, ['self', 'static', 'parent'], true) => $lower,
                $context !== null && strcasecmp($raw, $context->getName()) === 0 => 'self',
                $type->isBuiltin() => $raw,
                default => $this->shortClass($raw),
            };

            return ($type->allowsNull() && ! in_array($name, ['mixed', 'null'], true) ? '?' : '').$name;
        }

        if ($type instanceof \ReflectionUnionType) {
            return implode('|', array_map(fn ($t) => $this->type($t, $context), $type->getTypes()));
        }

        return (string) $type;
    }

    private function shortClass(string $class): string
    {
        return in_array($class, ['self', 'static'], true) ? $class : substr((string) strrchr('\\'.$class, '\\'), 1);
    }

    private function shortConstant(string $constant): string
    {
        return str_contains($constant, '::')
            ? $this->shortClass(explode('::', $constant)[0]).'::'.explode('::', $constant)[1]
            : $constant;
    }

    private function literal(mixed $value): string
    {
        return match (true) {
            $value === null => 'null',
            is_bool($value) => $value ? 'true' : 'false',
            is_int($value), is_float($value) => (string) $value,
            is_string($value) => "'".addslashes($value)."'",
            is_array($value) && $value === [] => '[]',
            is_array($value) => '['.implode(', ', array_map(
                fn ($k, $v) => (array_is_list($value) ? '' : $this->literal($k).' => ').$this->literal($v),
                array_keys($value),
                $value
            )).']',
            default => '…',
        };
    }

    /**
     * Description (the text before the first tag), @param descriptions,
     *
     * @return array{description: string, params: array<string, string>, throws: list<string>, deprecated: ?string}
     *
     * @throws lines and the @deprecated note of a docblock.
     */
    private function docblock(string $comment): array
    {
        $result = ['description' => '', 'params' => [], 'throws' => [], 'deprecated' => null];

        if ($comment === '') {
            return $result;
        }

        $lines = preg_split('/\R/', $comment) ?: [];
        $lines = array_map(fn ($line) => preg_replace('/^\s*(\/\*\*|\*\/|\*)\s?/', '', rtrim($line)), $lines);
        $lines = array_map(fn ($line) => rtrim((string) preg_replace('/\*\/$/', '', (string) $line)), $lines);

        $description = [];
        $tags = [];
        $current = null;

        foreach ($lines as $line) {
            if (preg_match('/^@(\w+)\s*(.*)$/', $line, $match)) {
                $tags[] = [$match[1], $match[2]];
                $current = array_key_last($tags);

                continue;
            }

            if ($current === null) {
                $description[] = $line;
            } elseif (trim($line) !== '') {
                $tags[$current][1] .= ' '.trim($line);
            }
        }

        $result['description'] = $this->inlineTags(trim(implode("\n", $description)));

        foreach ($tags as [$tag, $text]) {
            $text = trim((string) preg_replace('/\s+/', ' ', $text));

            $text = $this->inlineTags($text);

            if ($tag === 'param' && preg_match('/^(?:\S+\s+)?\.{0,3}\$(\w+)\s*(.*)$/', $text, $match)) {
                $result['params'][$match[1]] = str_replace(['<', '>'], ['&lt;', '&gt;'], $match[2]);
            } elseif ($tag === 'throws') {
                $result['throws'][] = preg_replace('/^(\S+)/', '`$1`', $text);
            } elseif ($tag === 'deprecated') {
                $result['deprecated'] = $text;
            }
        }

        return $result;
    }
}
